/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from 'ts-interface-checker';
// tslint:disable:object-literal-key-quotes

export const BaseObject = t.iface([], {
    name: 'string',
    source: 'string',
    page: t.opt('number'),
    srd: t.opt('boolean'),
    srd52: t.opt('boolean'),
    basicRules: t.opt('boolean'),
    basicRules2024: t.opt('boolean'),
    reprintedAs: t.opt(t.array(t.union('string', 'UID'))),
    additionalSources: t.opt(t.array('AdditionalSource')),
    otherSources: t.opt(t.array('AdditionalSource')),
});

export const UID = t.iface([], {
    uid: 'string',
    tag: 'string',
});

export const AdditionalSource = t.iface([], {
    source: 'string',
    page: t.opt('number'),
});

export const HRef = t.iface([], {
    type: t.lit('internal'),
    path: 'string',
    hash: t.opt('string'),
});

export const ListItem = t.iface([], {
    type: t.lit('item'),
    name: 'string',
    entry: t.opt('string'),
    entries: t.opt(t.array('string')),
});

export const TableCell = t.iface([], {
    type: t.lit('cell'),
    width: 'number',
    entry: 'string',
});

export const TableRow = t.iface([], {
    type: t.lit('row'),
    style: 'string',
    row: t.array('string'),
});

export const GenTables = t.iface([], {
    tableInclude: 'boolean',
});

export const TableData = t.iface([], {
    genTables: 'GenTables',
});

export const EntryEntries = t.iface([], {
    type: t.lit('entries'),
    name: t.opt('string'),
    page: t.opt('number'),
    source: t.opt('string'),
    entries: t.array('Entry'),
});

export const EntryList = t.iface([], {
    type: t.lit('list'),
    name: t.opt('string'),
    style: t.opt('string'),
    columns: t.opt('number'),
    items: t.array(t.union('string', 'ListItem')),
});

export const EntryTable = t.iface([], {
    type: t.lit('table'),
    caption: t.opt('string'),
    colLabels: t.array('string'),
    colStyles: t.array('string'),
    rows: t.array(t.union(t.array(t.union('string', 'number', 'Entry', 'TableCell')), 'TableRow')),
    footnotes: t.opt(t.array('string')),
    isNameGenerator: t.opt('boolean'),
    data: t.opt('TableData'),
    srd52: t.opt('boolean'),
    basicRules2024: t.opt('boolean'),
});

export const EntryInset = t.iface([], {
    type: t.lit('inset'),
    name: 'string',
    page: t.opt('number'),
    source: t.opt('string'),
    entries: t.array('Entry'),
});

export const EntryInsetReadaloud = t.iface([], {
    type: t.lit('insetReadaloud'),
    page: 'number',
    entries: t.array('Entry'),
});

export const EntryQuote = t.iface([], {
    type: t.lit('quote'),
    by: 'string',
    from: t.opt('string'),
    skipMarks: t.opt('boolean'),
    entries: t.array('Entry'),
});

export const EntryStatblock = t.iface([], {
    type: t.lit('statblock'),
    name: 'string',
    source: 'string',
    page: 'number',
    tag: 'string',
});

export const EntryInline = t.iface([], {
    type: t.lit('inline'),
    entries: t.array('Entry'),
});

export const EntryLink = t.iface([], {
    type: t.lit('link'),
    href: 'HRef',
    text: 'string',
});

export const EntryImage = t.iface([], {
    type: t.lit('image'),
    href: 'HRef',
    title: t.opt('string'),
    width: t.opt('number'),
    height: t.opt('number'),
    credit: t.opt('string'),
    altText: t.opt('string'),
});

export const EntrySection = t.iface([], {
    type: t.lit('section'),
    name: 'string',
    entries: t.array('Entry'),
});

export const Entry = t.union(
    'string',
    'EntryEntries',
    'EntryList',
    'EntryTable',
    'EntryInset',
    'EntryInsetReadaloud',
    'EntryQuote',
    'EntryStatblock',
    'EntryInline',
    'EntryLink',
    'EntryImage',
    'EntrySection'
);

export const Range = t.iface([], {
    type: t.lit('range'),
    min: 'number',
    max: 'number',
});

export const TimeUnit = t.iface([], {
    unit: t.union(
        t.lit('action'),
        t.lit('bonus'),
        t.lit('reaction'),
        t.lit('minute'),
        t.lit('round'),
        t.lit('hour')
    ),
    number: 'number',
});

export const Time = t.union('string', 'TimeUnit');

export const Action = t.iface(['BaseObject'], {
    entries: t.array('Entry'),
    time: t.opt(t.array('Time')),
    fromVariant: t.opt('string'),
    seeAlsoAction: t.opt(t.array('string')),
});

export const VariantRule = t.iface(['BaseObject'], {
    type: t.opt('string'),
    ruleType: t.opt(t.union(t.lit('C'), t.lit('O'), t.lit('V'), t.lit('VO'))),
    entries: t.array('Entry'),
});

export const Language = t.iface(['BaseObject'], {
    typicalSpeakers: t.opt(t.array('string')),
    script: t.opt('string'),
    type: t.opt('string'),
    origin: t.opt('string'),
    entries: t.opt(t.array('Entry')),
    hasFluffImages: t.opt('boolean'),
    fonts: t.opt(t.array('string')),
    dialects: t.opt(t.array('string')),
});

export const LanguageFluff = t.iface(['BaseObject'], {
    images: t.array('EntryImage'),
});

const exportedTypeSuite: t.ITypeSuite = {
    BaseObject,
    UID,
    AdditionalSource,
    HRef,
    ListItem,
    TableCell,
    TableRow,
    GenTables,
    TableData,
    EntryEntries,
    EntryList,
    EntryTable,
    EntryInset,
    EntryInsetReadaloud,
    EntryQuote,
    EntryStatblock,
    EntryInline,
    EntryLink,
    EntryImage,
    EntrySection,
    Entry,
    Range,
    TimeUnit,
    Time,
    Action,
    VariantRule,
    Language,
    LanguageFluff,
};
export default exportedTypeSuite;
