/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const TimeUnit = t.iface([], {
  "number": "number",
  "unit": "string",
});

export const DescriptionEntries = t.iface([], {
  "type": t.lit('entries'),
  "name": "string",
  "entries": t.array("Description"),
});

export const Description = t.union("string", "DescriptionEntries");

export const Time = t.union("string", "TimeUnit");

export const Action = t.iface([], {
  "name": "string",
  "source": "string",
  "page": "number",
  "srd": t.opt("boolean"),
  "basicRules": t.opt("boolean"),
  "time": t.opt(t.array("Time")),
  "seeAlsoAction": t.opt(t.array("string")),
});

const exportedTypeSuite: t.ITypeSuite = {
  TimeUnit,
  DescriptionEntries,
  Description,
  Time,
  Action,
};
export default exportedTypeSuite;
