/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from 'ts-interface-checker';
// tslint:disable:object-literal-key-quotes

export const BaseEntry = t.iface([], {
    name: 'string',
    source: 'string',
    page: t.opt('number'),
    srd: t.opt('boolean'),
    srd52: t.opt('boolean'),
    basicRules: t.opt('boolean'),
    basicRules2024: t.opt('boolean'),
    reprintedAs: t.opt(t.array(t.union('string', 'UID'))),
    additionalSources: t.opt(t.array('AdditionalSource')),
    otherSources: t.opt(t.array('AdditionalSource')),
});

export const UID = t.iface([], {
    uid: 'string',
    tag: 'string',
});

export const AdditionalSource = t.iface([], {
    source: 'string',
    page: t.opt('number'),
});

export const HRef = t.iface([], {
    type: t.lit('internal'),
    path: 'string',
    hash: t.opt('string'),
});

export const ListItem = t.iface([], {
    type: t.lit('item'),
    name: 'string',
    entry: t.opt('string'),
    entries: t.opt(t.array('string')),
});

export const TableCell = t.iface([], {
    type: t.lit('cell'),
    width: 'number',
    entry: 'string',
});

export const TableRow = t.iface([], {
    type: t.lit('row'),
    style: 'string',
    row: t.array('string'),
});

export const GenTables = t.iface([], {
    tableInclude: 'boolean',
});

export const TableData = t.iface([], {
    genTables: 'GenTables',
});

export const DescriptionEntries = t.iface([], {
    type: t.lit('entries'),
    name: t.opt('string'),
    page: t.opt('number'),
    source: t.opt('string'),
    entries: t.array('Description'),
});

export const DescriptionList = t.iface([], {
    type: t.lit('list'),
    name: t.opt('string'),
    style: t.opt('string'),
    columns: t.opt('number'),
    items: t.array(t.union('string', 'ListItem')),
});

export const DescriptionTable = t.iface([], {
    type: t.lit('table'),
    caption: t.opt('string'),
    colLabels: t.array('string'),
    colStyles: t.array('string'),
    rows: t.array(
        t.union(t.array(t.union('string', 'number', 'Description', 'TableCell')), 'TableRow')
    ),
    footnotes: t.opt(t.array('string')),
    isNameGenerator: t.opt('boolean'),
    data: t.opt('TableData'),
    srd52: t.opt('boolean'),
    basicRules2024: t.opt('boolean'),
});

export const DescriptionInset = t.iface([], {
    type: t.lit('inset'),
    name: 'string',
    page: t.opt('number'),
    source: t.opt('string'),
    entries: t.array('Description'),
});

export const DescriptionInsetReadaloud = t.iface([], {
    type: t.lit('insetReadaloud'),
    page: 'number',
    entries: t.array('Description'),
});

export const DescriptionQuote = t.iface([], {
    type: t.lit('quote'),
    by: 'string',
    from: t.opt('string'),
    skipMarks: t.opt('boolean'),
    entries: t.array('Description'),
});

export const DescriptionStatblock = t.iface([], {
    type: t.lit('statblock'),
    name: 'string',
    source: 'string',
    page: 'number',
    tag: 'string',
});

export const DescriptionInline = t.iface([], {
    type: t.lit('inline'),
    entries: t.array('Description'),
});

export const DescriptionLink = t.iface([], {
    type: t.lit('link'),
    href: 'HRef',
    text: 'string',
});

export const DescriptionImage = t.iface([], {
    type: t.lit('image'),
    href: 'HRef',
    title: t.opt('string'),
    width: t.opt('number'),
    height: t.opt('number'),
    credit: t.opt('string'),
    altText: t.opt('string'),
});

export const DescriptionSection = t.iface([], {
    type: t.lit('section'),
    name: 'string',
    entries: t.array('Description'),
});

export const Description = t.union(
    'string',
    'DescriptionEntries',
    'DescriptionList',
    'DescriptionTable',
    'DescriptionInset',
    'DescriptionInsetReadaloud',
    'DescriptionQuote',
    'DescriptionStatblock',
    'DescriptionInline',
    'DescriptionLink',
    'DescriptionImage',
    'DescriptionSection'
);

export const Range = t.iface([], {
    type: t.lit('range'),
    min: 'number',
    max: 'number',
});

export const TimeUnit = t.iface([], {
    unit: t.union(
        t.lit('action'),
        t.lit('bonus'),
        t.lit('reaction'),
        t.lit('minute'),
        t.lit('round'),
        t.lit('hour')
    ),
    number: 'number',
});

export const Time = t.union('string', 'TimeUnit');

export const Action = t.iface(['BaseEntry'], {
    entries: t.array('Description'),
    time: t.opt(t.array('Time')),
    fromVariant: t.opt('string'),
    seeAlsoAction: t.opt(t.array('string')),
});

export const VariantRule = t.iface(['BaseEntry'], {
    type: t.opt('string'),
    ruleType: t.opt(t.union(t.lit('C'), t.lit('O'), t.lit('V'), t.lit('VO'))),
    entries: t.array('Description'),
});

export const Language = t.iface(['BaseEntry'], {
    typicalSpeakers: t.opt(t.array('string')),
    script: t.opt('string'),
    type: t.opt('string'),
    origin: t.opt('string'),
    entries: t.opt(t.array('Description')),
    hasFluffImages: t.opt('boolean'),
    fonts: t.opt(t.array('string')),
    dialects: t.opt(t.array('string')),
});

export const LanguageFluff = t.iface(['BaseEntry'], {
    images: t.array('DescriptionImage'),
});

export const VehicleTrait = t.iface([], {
    name: 'string',
    entries: t.array('string')
})

export const VehicleSpeed = t.iface([], {
    fly: t.opt(t.union('number', 'string')),
    water: t.opt(t.union('number', 'string')),
    note: t.opt('string')
})

export const VehicleHull = t.iface([], {
    ac: 'number',
    acFrom: t.opt(t.array('string')),
    hp: 'number',
    dt: 'number'
})

export const VehicleControl = t.iface([], {
    name: 'string',
    ac: 'number',
    hp: 'number',
    entries: t.array('string')
})

export const VehicleMovementSpeed = t.iface([], {});  // TODO

export const VehicleMovement = t.iface([], {
    name: 'string',
    ac: 'number',
    hp: 'number',
    hpNote: 'string',
    speed: t.array('VehicleMovementSpeed')
})

export const Vehicle = t.iface(['BaseEntry'], {
    vehicleType: 'string', //TODO use literals
    size: t.opt(t.union('string', t.array('string'))),
    dimensions: t.opt(t.array('string')),
    terrain: t.array('string'),
    capCrew: 'number',
    capPassenger: t.opt('number'),
    capCargo: t.opt('number'),
    cost: t.opt('number'),
    pace: t.opt(t.union('number', 'VehicleSpeed')),
    speed: t.opt(t.union('number', 'VehicleSpeed')),
    ac: t.opt('number'),
    str: t.opt('number'),
    dex: t.opt('number'),
    con: t.opt('number'),
    int: t.opt('number'),
    wis: t.opt('number'),
    cha: t.opt('number'),
    hp: t.opt(t.union('number', 'object')),
    immune: t.opt(t.array('string')),
    conditionImmune: t.opt(t.array('string')),
    hull: t.opt('VehicleHull'),
    control: t.opt(t.array('VehicleControl')),
    movement: t.opt(t.array('object')), // TODO
    weapon: t.opt(t.array('object')), // TODO
    actionThresholds: t.opt('object'), // TODO
    action: t.opt(t.array('Description')),
    trait: t.opt(t.array('VehicleTrait')),
    actionStation: t.opt(t.array('VehicleTrait')),
    reaction: t.opt(t.array('VehicleTrait')),
    entries: t.array('Description'),
    tokenCredit: t.opt('string'),
    hasToken: t.opt('boolean'),
    hasFluff: t.opt('boolean'),
    hasFluffImages: t.opt('boolean')
})

const exportedTypeSuite: t.ITypeSuite = {
    BaseEntry,
    UID,
    AdditionalSource,
    HRef,
    ListItem,
    TableCell,
    TableRow,
    GenTables,
    TableData,
    DescriptionEntries,
    DescriptionList,
    DescriptionTable,
    DescriptionInset,
    DescriptionInsetReadaloud,
    DescriptionQuote,
    DescriptionStatblock,
    DescriptionInline,
    DescriptionLink,
    DescriptionImage,
    DescriptionSection,
    Description,
    Range,
    TimeUnit,
    Time,
    Action,
    VariantRule,
    Language,
    LanguageFluff,
};
export default exportedTypeSuite;
