name: MAIN

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

permissions:
    contents: read

jobs:
    prettier:
        # Check if prettier needs to be applied
        runs-on: ubuntu-latest
        name: prettier-check
        steps:
            - name: Checkout repo and submodules
              uses: actions/checkout@v4
              with:
                  submodules: true

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'

            - name: Install dependencies
              run: npm ci

            - name: Run prettier
              run: npx prettier package.json "./src/**/*.ts" -c

    eslint:
        runs-on: ubuntu-latest
        name: eslint-check
        steps:
            - name: Checkout repo and submodules
              uses: actions/checkout@v4
              with:
                  submodules: true

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'

            - name: Install dependencies
              run: npm ci

            - name: Run eslint
              run: npm run lint