name: Run generator on Dependabot PR

on:
    pull_request:
        branches:
            - main # or your default branch
        types: [opened, synchronize, reopened]

jobs:
    run-generator:
        # Only run on PRs from Dependabot
        if: github.actor == 'dependabot[bot]'
        runs-on: ubuntu-latest
        name: 'Generate new data'

        steps:
            - name: Checkout repo and submodules
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'

            - name: Install dependencies
              run: npm ci

            - name: Run generate script
              run: npm run generate

            - name: Commit changes
              id: commit
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add ./generated
                  if git diff --cached --quiet; then
                  echo "no_changes=true" >> $GITHUB_OUTPUT
                  else
                  git commit -m "Regenerate after Dependabot update ${{ github.event.pull_request.number }}"
                  echo "no_changes=false" >> $GITHUB_OUTPUT
                  fi

            - name: Push and open PR against Dependabot branch
              if: steps.commit.outputs.no_changes == 'false'
              uses: peter-evans/create-pull-request@v6
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: 'Regenerate after Dependabot update ${{ github.event.pull_request.number }}'
                  title: 'Add generated output for #${{ github.event.pull_request.number }}'
                  body: |
                      This PR builds on top of the Dependabot update (#${{ github.event.pull_request.number }}) and includes generated files.
                  base: ${{ github.event.pull_request.head.ref }}
                  branch: gen/update-${{ github.event.pull_request.number }}
                  delete-branch: true
