name: VALIDATE-URLS
permissions:
  contents: read

on:
  pull_request:
    paths:
      - ".github/workflows/validate-urls.yml"
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at 00:00 UTC

jobs:
  lychee-url-check:
    runs-on: ubuntu-latest
    name: lychee
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install & Run Lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: >
            --verbose
            --no-progress
            --include-fragments
            --max-redirects 10
            './generated/*.json'

      - name: Fail if dead links found
        if: steps.lychee.outcome == 'failure'
        run: exit 1